services:
  - type: web
    name: netmon-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sniffer:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0